export global Palette {
    in-out property <brush> purple-primary: #CBAABD;
    in-out property <brush> black-primary: #191308;
    in-out property <brush> gray-primary: #E0E2DB;
    in-out property <brush> gray-secondary: #52796F;
    in-out property <brush> blue: #326771;
    in-out property <brush> pink-primary: #FFB7FF;
    in-out property <brush> text-primary: #FCECC9;
    in-out property <brush> text-secondary: #000000;
}
